### ISSUE TITLE
TypeError: this.networkFile.unsetStdlib is not a function （zos@1.1.0）

### ISSUE THREAD

**Issue by roson9527** [zeppelinos/zos-cli#323]
```
     TypeError: this.networkFile.unsetStdlib is not a function
      at NetworkAppController.deployStdlib (node_modules/zos/lib/models/network/NetworkAppController.js:55:64)
      at testApp (node_modules/zos/lib/models/TestApp.js:15:20)
      at Context.beforeEach (test/premission/base_on_erc721_rbac.test.js:17:26)
```
cmd: NODE_ENV=test truffle test(working in zos@1.0.0)

**Comment by facuspagnuolo** [comment]
Thanks for submitting the issue @roson9527, would you mind giving us more context about how can we reproduce it?

**Comment by roson9527** [comment]
After modifying the reference, I found that it still could not be reproduced
but it led to a new problem: (
[https://github.com/zeppelinos/zos-cli/issues/333](url)

**Comment by mtomov** [comment]
btw, https://github.com/zeppelinos/zos-cli/issues/333#issuecomment-407535315 fixed the above issue for me as well! Thanks guys!
